#!/usr/bin/env node
/**
 * Exports the AI-assisted-development prompt history for this project into
 * docs/PROMPTS.md, which the Cloudflare assignment requires as a submission
 * artifact.
 *
 * Reads the Claude Code session transcript (JSONL) and pulls out:
 *   - every human prompt typed by the developer
 *   - every sub-agent brief dispatched by the orchestrating model
 *
 * Tool results, system reminders, and model chain-of-work are deliberately
 * excluded: the requirement is the prompts, not the full machine transcript.
 *
 * Usage: node scripts/export-prompts.mjs <session.jsonl> [more.jsonl ...]
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const SKIP_PREFIXES = ['<system-reminder>', '<command-name>', '<command-message>', '<local-command'];

/**
 * Prompts are pasted terminal output as often as they are typed prose, so they
 * can carry material that must not end up in a published artifact. Redact
 * before writing, not after: this file is regenerated often and a manual edit
 * would be silently undone on the next run.
 */
const REDACTIONS = [
  // wrangler/OAuth authorize URLs carry client_id, state and a PKCE challenge.
  [/https:\/\/dash\.cloudflare\.com\/oauth2\/auth\?\S+/g, '<redacted: cloudflare oauth url>'],
  // Any stray bearer/API token shape.
  [/\b(bearer\s+)[A-Za-z0-9._~+/-]{20,}=*/gi, '$1<redacted>'],
  [/\b[A-Za-z0-9_-]{24,}\.[A-Za-z0-9_-]{6,}\.[A-Za-z0-9_-]{20,}\b/g, '<redacted: jwt>'],
  // Cloudflare API tokens are 40 chars of base62 with a v1.0- style prefix.
  [/\bv1\.0-[A-Za-z0-9_-]{30,}/g, '<redacted: cf api token>'],
  [/\b(api[_-]?(?:key|token)\s*[:=]\s*)['"]?[A-Za-z0-9._~+/-]{16,}['"]?/gi, '$1<redacted>'],
];

function redact(text) {
  let out = text;
  for (const [pattern, replacement] of REDACTIONS) out = out.replace(pattern, replacement);
  return out;
}
const files = process.argv.slice(2);
if (files.length === 0) {
  console.error('usage: node scripts/export-prompts.mjs <session.jsonl> [...]');
  process.exit(1);
}

/** @returns {string|null} the human-typed text of a transcript row, if any */
function humanPrompt(row) {
  if (row.type !== 'user' || !row.message) return null;
  const c = row.message.content;
  const text = typeof c === 'string'
    ? c
    : Array.isArray(c)
      ? c.filter((b) => b.type === 'text').map((b) => b.text).join('\n')
      : '';
  const trimmed = text.trim();
  if (!trimmed) return null;
  if (SKIP_PREFIXES.some((p) => trimmed.startsWith(p))) return null;
  // Rows that only carry a tool result are machine traffic, not prompts.
  if (Array.isArray(c) && c.every((b) => b.type === 'tool_result')) return null;
  return trimmed;
}

/** @returns {Array<{description:string, prompt:string}>} sub-agent briefs in a row */
function agentBriefs(row) {
  if (row.type !== 'assistant' || !row.message || !Array.isArray(row.message.content)) return [];
  return row.message.content
    .filter((b) => b.type === 'tool_use' && b.name === 'Agent' && b.input?.prompt)
    .map((b) => ({ description: b.input.description ?? 'agent', prompt: b.input.prompt }));
}

const entries = [];
for (const file of files) {
  let raw;
  try {
    raw = readFileSync(file, 'utf8');
  } catch (err) {
    console.error(`skipping ${file}: ${err.message}`);
    continue;
  }
  for (const line of raw.split('\n')) {
    if (!line.trim()) continue;
    let row;
    try { row = JSON.parse(line); } catch { continue; }
    const ts = row.timestamp ?? null;
    const human = humanPrompt(row);
    if (human) entries.push({ kind: 'human', ts, text: human });
    for (const brief of agentBriefs(row)) {
      entries.push({ kind: 'agent', ts, text: brief.prompt, label: brief.description });
    }
  }
}

const out = [];
out.push('# Prompt history');
out.push('');
out.push('Submitted per the Cloudflare assignment requirement that AI-assisted development');
out.push('disclose its prompt history. Generated by `scripts/export-prompts.mjs` directly from');
out.push('the Claude Code session transcript — not written after the fact.');
out.push('');
out.push('Credentials and OAuth URLs pasted into the terminal are redacted on export');
out.push('(see `REDACTIONS` in the script).');
out.push('');
out.push(`- Prompts recorded: **${entries.length}**`);
out.push(`- Human prompts: **${entries.filter((e) => e.kind === 'human').length}**`);
out.push(`- Sub-agent briefs: **${entries.filter((e) => e.kind === 'agent').length}**`);
out.push(`- Exported: ${new Date().toISOString()}`);
out.push('');
out.push('---');
out.push('');

let n = 0;
for (const e of entries) {
  n += 1;
  const when = e.ts ? ` · ${e.ts}` : '';
  const head = e.kind === 'human'
    ? `## ${n}. Developer prompt${when}`
    : `## ${n}. Sub-agent brief — ${e.label}${when}`;
  out.push(head);
  out.push('');
  out.push('```text');
  out.push(redact(e.text));
  out.push('```');
  out.push('');
}

const target = resolve(process.cwd(), 'docs/PROMPTS.md');
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, out.join('\n'), 'utf8');
console.log(`wrote ${target} (${entries.length} prompts)`);
